### ISSUE TITLE
Tracking issue: 2024Q3 cleanup in support of nv24

### ISSUE THREAD

**Issue by BigLep** [filecoin-project/lotus-infra#1615]
Below is a set of low-hanging fruit items we're going to do to help with butterfly deployments that will be needed for f3 and nv24 work in 2024Q3.  This is a timebox effort of 2 days:

```[tasklist]
### Tasks
- [ ] https://github.com/filecoin-project/lotus-infra/issues/1611
- [ ] https://github.com/filecoin-project/lotus-infra/issues/1610
- [ ] https://github.com/filecoin-project/lotus-infra/issues/1597
- [ ] https://github.com/filecoin-project/lotus-infra/issues/1620
- [ ] https://github.com/filecoin-project/lotus-infra/pull/1622
- [ ] https://github.com/filecoin-project/lotus-infra/pull/1624
- [ ] https://github.com/filecoin-project/lotus-infra/pull/1626
- [ ] https://github.com/filecoin-project/lotus-infra/issues/1598
```
