### ISSUE TITLE
Make this repo public

### ISSUE THREAD

**Issue by BigLep** [filecoin-project/lotus-infra#1631]
## Done Criteria
This repo or some slice of if it is public.

## Why Important
1. Enable others to learn from it so they don't have to reinvent the wheel
2. We reference this repo from other public repos (recent example: https://github.com/filecoin-project/lotus/pull/12439 and https://github.com/filecoin-project/lotus/pull/12448)
3. (bonus/maybe) get external contributions 

## Notes
1. The key thing is to ensure we're not exposing any secrets.

## Tasks
```[tasklist]
## Tasks
- [x] Decide on approach
- [x] Create lotus-infra-archive
- [x] Give context on lotus-infra-archive: https://github.com/filecoin-project/lotus-infra-archive/pull/1
- [x] Update lotus-infra readme to be public facing: https://github.com/filecoin-project/lotus-infra/pull/1636
- [x] Prepare script for bulk transferring issues: https://github.com/filecoin-project/lotus-infra/issues/1631#issuecomment-2362234167
- [x] Bulk transfer issues
- [x] Mark lotus-infra-archive as archived: https://github.com/filecoin-project/github-mgmt/pull/78
- [x] Mark lotus-infra as public: https://github.com/filecoin-project/github-mgmt/pull/78
```

**Comment by BigLep** [comment]
Closing as repo is now public
